import React, {useState} from 'react'; 
import Head from 'next/head'
import Layout from '../component/layout';
import styles from '../styles/Home.module.css'
import { providers, Contract} from 'ethers';
import { Card, Button, Icon, Header, Grid, GridRow, GridColumn } from 'semantic-ui-react';
import CampaignFactoryJson from '../CampaignFactory.json'
import Link from 'next/link';

export default function Home({addresses}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Header>
          Open Campaigns
        </Header>
        <Grid>
          <GridRow>
            <GridColumn width={10}>
              <Card.Group>
                {
                    addresses.map((item, index) => {
                      return (
                      <Card key={'address'+index} fluid>
                        <Card.Content>
                          <Card.Header>Campaign {index+1}</Card.Header>
                          <Card.Description>
                            The campaign address is {item} 
                            <br/>
                            <a href={`/campaigns/${item}`}>View Campaign</a>
                          </Card.Description>
                        </Card.Content>
                      </Card>
                      )
                    })
                }
              </Card.Group>
            </GridColumn>
            <GridColumn width={6}>
            <Link href='/campaigns/new'>
              <Button
              icon 
              labelPosition='left'
              primary 
              floated='right'
              >
                <Icon name='plus circle'/>
                Create a new campaign 
              </Button>
            </Link>
            </GridColumn>
          </GridRow>
        </Grid>
      </Layout>
      
    </div>
  )
}

// Before writing get initial props, 
// a provider and a contract is needed to access 
// the contract. 
// Probably have to get the json for the abi and address of the campaign factory
// which is 0xb17f0128f879EA830d2dfA23621ccF13099a65Ba at Goerli
// In order to do that on the server side, 
// it is probably the best to, write a function that does all this. 
  const CampaignFactoryAddress = '0xF04e6744F9C47022c439754F8a0dEa6De3eE7597'
  const getCampaignAddress = async () => {
    const provider = new providers.AlchemyProvider(
        'goerli', 
        process.env.API_KEY
      )
    const CampaignFactory = new Contract(CampaignFactoryAddress, JSON.stringify(CampaignFactoryJson.abi), provider)        
    const campaigns = await CampaignFactory.getDeployedCampaigns()
    console.log(campaigns)
    return campaigns; 
  }

// Write get initial props to fetch the campaign address
Home.getInitialProps = async (ctx) => {
  const addresses = await getCampaignAddress(); 
  return {
    addresses: addresses
  }
}

